# Generated by Django 6.0.5 on 2026-06-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_max_activities_alter_trip_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='max_proposals',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
